### ISSUE TITLE
PA9 or PA10 for USART1

### ISSUE THREAD

**Issue by cinderblock** [simap/pixelblaze_output_expander#2]
Hello,

I'm working on an art piece and we're using your serial -> Pixel expander but with an RS-485 transceiver in front to send the serial data a longer distance.

In designing the board for this, I'm replicating your circuit.

I'm confused about one part of the wiring that I'm hoping you might shed some light on.

In the [schematic](https://github.com/simap/pixelblaze_output_expander/blob/master/hardware/pixelAdapter_f103c8.sch) see that the serial input goes into PA9 (pin 30) on the STM32F103C8T6.

However in the datasheet for the STM32F103C8T6, I see the PA9 is USART1_TX. So is it TX or RX?

![image](https://user-images.githubusercontent.com/419955/82161370-f301ab80-9850-11ea-8d76-590fa15da50f.png)

I was looking for some remapping that might be happening in the code source but didn't see any.

I feel like maybe I'm missing something simple.

**Comment by simap** [comment]
It's set for single wire half-duplex mode. In that mode both TX/RX share a pin on pa9. I thought it might be handy in case I wanted to add automatic identification, but never got around to implementing it in firmware.

https://github.com/simap/pixelblaze_output_expander/blob/master/firmware/Core/Src/main.c#L514

**Comment by cinderblock** [comment]
Aha! That makes sense. Thank you for the clarification. Knew it was something simple.

We're looking to have bi-directional (full duplex with two differential pairs) communication for these boards. One possible solution would be to just add a separate CPU to do the reverse direction but I suspect there is plenty of headroom available on STM32 to add a couple digital inputs that send their state back.

If I were to develop a Bi-directional protocol for these, would you be curious to see it? We're currently planning a full-duplex protocol but a half-duplex should work too...

**Comment by simap** [comment]
of course :)
What are you going to implement with the reverse comms? ID/config? Read memory?

**Comment by cinderblock** [comment]
We need to detect a remote button press (which is itself a fancy phantom power digital button) and react to it at the central controller. For wiring reasons, the buttons will be close to some of the lights (and this controller) and I wanted to leverage the existing twisted pairs and GPIO available on this processor. (We briefly considered modifying the code to make a 16-channel expander too, since there are so many open GPIO.)

The project is still in stealth mode. I'm looking forward to getting to tell people about it :D

We hope it can have some of its life at Burning Man but, with how the world is, we'll see how the cookie crumbles.
